# Assignment 04
Date: 03/28/2020

Name: Mukunthan Ragavan

## Write a function to compute 5/0 and use try/except to catch the exceptions.

In [54]:
try:
    a=5/0
except ZeroDivisionError as zde:
    print('Error detail: ', zde)
except Exception as e:
    print(e)
else:
    print('Code fully executed')
finally:
    print('Finally block code')
    

Error detail:  division by zero
Finally block code


## Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].


Hint: Subject,Verb and Object should be declared in the program as shown below.

subjects=["Americans ","Indians"]

verbs=["play","watch"]

objects=["Baseball","Cricket"]

In [55]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

In [56]:
for subject in subjects:
    for verb in verbs:
        for obj in objects:
            print(subject,verb, obj)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


# Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [57]:
import numpy as np

In [58]:
## Approach one
def generate_vander(vector, N, increase=False):  #np.vander(vector,5, True)  Existing numpy builtin function
    '''
    this function return vander matrix
    Length of vector decides the no.of rows in resultant matrix
    N decides the no.of coloumns in resultant matrix
    
    '''
    if increase:
        return np.array([x**i for x in vector for i in range(N)]).reshape(vector.size, N)
        # decides no of rows in output matrix  and N decides no.of cols
    elif not:
        return np.array([x** (N - i - 1) for x in vector for i in range(N)]).reshape(vector.size, N)
    else:
        raise ValueError
        

SyntaxError: invalid syntax (<ipython-input-58-30c9116e6ac0>, line 12)

In [59]:
## Approach two
def generate_vander_using_flip(vector, N, increase=False):  #np.vander(vector,5, True)  Existing numpy builtin function
    '''
    this function return vander matrix
    Length of vector decides the no.of rows in resultant matrix
    N decides the no.of coloumns in resultant matrix
    
    '''
    result_vander = np.array([x**i for x in vector for i in range(N)]).reshape(vector.size, N)
    
    if increase:
        return result_vander
        # decides no of rows in output matrix  and N decides no.of cols
    elif not increase:
        return np.flip(result_vander, axis=1) #reverse contents of each row in the Numpy Array
    else:
        raise ValueError
        

In [60]:
vector = np.array([1, 2, 3, 5,9])

In [61]:
generate_vander(vector,5)

array([[   1,    1,    1,    1,    1],
       [  16,    8,    4,    2,    1],
       [  81,   27,    9,    3,    1],
       [ 625,  125,   25,    5,    1],
       [6561,  729,   81,    9,    1]])

In [62]:
generate_vander(vector,5,increase=True)

array([[   1,    1,    1,    1,    1],
       [   1,    2,    4,    8,   16],
       [   1,    3,    9,   27,   81],
       [   1,    5,   25,  125,  625],
       [   1,    9,   81,  729, 6561]])

In [63]:
generate_vander_using_flip(vector,5)

array([[   1,    1,    1,    1,    1],
       [  16,    8,    4,    2,    1],
       [  81,   27,    9,    3,    1],
       [ 625,  125,   25,    5,    1],
       [6561,  729,   81,    9,    1]])

In [65]:
generate_vander_using_flip(vector,5,increase=True)

array([[   1,    1,    1,    1,    1],
       [   1,    2,    4,    8,   16],
       [   1,    3,    9,   27,   81],
       [   1,    5,   25,  125,  625],
       [   1,    9,   81,  729, 6561]])

# Thanks for your time !