# Numpy Assignment
Date: 19/04/2020

Name: Mukunthan Ragavan

In [110]:
import numpy as np

In [111]:
## Approach one
def generate_vander(vector, N, increase=False):  #np.vander(vector,5, True)  Existing numpy builtin function
    '''
    this function return vander matrix
    Length of vector decides the no.of rows in resultant matrix
    N decides the no.of coloumns in resultant matrix
    
    '''
    try:
        if increase:
            return np.array([x**i for x in vector for i in range(N)]).reshape(vector.size, N)
            # decides no of rows in output matrix  and N decides no.of cols
        else:
            return np.array([x** (N - i - 1) for x in vector for i in range(N)]).reshape(vector.size, N)
    except Exception as e:
        print('Exception occurred and details are: ', e)
        

In [112]:
## Approach two
def generate_vander_using_flip(vector, N, increase=False):  #np.vander(vector,5, True)  Existing numpy builtin function
    '''
    this function return vander matrix
    Length of vector decides the no.of rows in resultant matrix
    N decides the no.of coloumns in resultant matrix
    
    '''
    try:
        
        result_vander = np.array([x**i for x in vector for i in range(N)]).reshape(vector.size, N)

        if increase:
            return result_vander
            # decides no of rows in output matrix  and N decides no.of cols
        else:
            return np.flip(result_vander, axis=1) #reverse contents of each row in the Numpy Array
    except Exception as e:
        print('Exception occurred and details are: ', e)

In [113]:
vector = np.array([1, 2, 3, 5,9])

In [114]:
generate_vander(vector,5)

array([[   1,    1,    1,    1,    1],
       [  16,    8,    4,    2,    1],
       [  81,   27,    9,    3,    1],
       [ 625,  125,   25,    5,    1],
       [6561,  729,   81,    9,    1]])

In [115]:
generate_vander(vector,5,increase=True)

array([[   1,    1,    1,    1,    1],
       [   1,    2,    4,    8,   16],
       [   1,    3,    9,   27,   81],
       [   1,    5,   25,  125,  625],
       [   1,    9,   81,  729, 6561]])

In [116]:
generate_vander_using_flip(vector,5)

array([[   1,    1,    1,    1,    1],
       [  16,    8,    4,    2,    1],
       [  81,   27,    9,    3,    1],
       [ 625,  125,   25,    5,    1],
       [6561,  729,   81,    9,    1]])

In [117]:
generate_vander_using_flip(vector,5,increase=True)

array([[   1,    1,    1,    1,    1],
       [   1,    2,    4,    8,   16],
       [   1,    3,    9,   27,   81],
       [   1,    5,   25,  125,  625],
       [   1,    9,   81,  729, 6561]])

In [118]:
generate_vander('test',5,increase=True)

Exception occurred and details are:  unsupported operand type(s) for ** or pow(): 'str' and 'int'


In [119]:
generate_vander('test',5)

Exception occurred and details are:  unsupported operand type(s) for ** or pow(): 'str' and 'int'


In [120]:
generate_vander_using_flip(147,5,increase=True)

Exception occurred and details are:  'int' object is not iterable


In [121]:
#################################################################################################

In [122]:
###########Solution#########################

In [123]:
class invalid_k_valueError(ValueError):
    pass

In [124]:
def moving_average_window(n,k):
    return (n-k+1)

In [125]:
def moving_avg_calculation(input_arr, window, k):
    if (k<=0): raise invalid_k_valueError('k value should be greater than 0')
    for i in range(window):  # window = 7
        print('Y'+str(i+1), end=' => ')
        sum=0
        for j in range( k):  # k =4
            #print(input_arr[j+i])
            sum = sum + input_arr[j+i]

        print(int(sum/k))

In [126]:
input_arr = np.array([10 ,20, 30 ,40, 50 ,60 ,70 ,80, 90, 100])
k=4
n=len(input_arr)
window =moving_average_window(n,k)

In [127]:
print('Given array:', input_arr)
print('Given array length (n):', n)
print('Given K value:', k)
print('Moving average window: ', moving_average_window(n,k))

Given array: [ 10  20  30  40  50  60  70  80  90 100]
Given array length (n): 10
Given K value: 4
Moving average window:  7


In [128]:
moving_avg_calculation(input_arr, window, k)

Y1 => 25
Y2 => 35
Y3 => 45
Y4 => 55
Y5 => 65
Y6 => 75
Y7 => 85


In [129]:
input_arr = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k=3
n=len(input_arr)
window =moving_average_window(n,k)

In [130]:
print('Given array:', input_arr)
print('Given array length (n):', n)
print('Given K value:', k)
print('Moving average window: ', moving_average_window(n,k))

Given array: [  3   5   7   2   8  10  11  65  72  81  99 100 150]
Given array length (n): 13
Given K value: 3
Moving average window:  11


In [131]:
moving_avg_calculation(input_arr, window, k)

Y1 => 5
Y2 => 4
Y3 => 5
Y4 => 6
Y5 => 9
Y6 => 28
Y7 => 49
Y8 => 72
Y9 => 84
Y10 => 93
Y11 => 116


In [132]:
moving_avg_calculation(input_arr, window, k=0)  #negative sceanario

invalid_k_valueError: k value should be greater than 0

### Reference : https://pages.mtu.edu/~shene/COURSES/cs201/NOTES/chap08/mov-avg.html

## Thanks for your time 